*** Variables ***
${INVENTORY_CONTAINER}    id=inventory_container
${PRODUCT_SORT}          data-test=product_sort_container
${ADD_TO_CART_PREFIX}    data-test=add-to-cart-
${REMOVE_FROM_CART_PREFIX}    data-test=remove-
${SHOPPING_CART_BADGE}    class=shopping_cart_badge
${SHOPPING_CART_LINK}    class=shopping_cart_link
${BURGER_MENU}          id=react-burger-menu-btn
${LOGOUT_LINK}          id=logout_sidebar_link 