name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox]
        include:
          - browser: chromium
            playwright-version: 1.41.1
          - browser: firefox
            playwright-version: 1.41.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          echo "PATH=$VIRTUAL_ENV/bin:$PATH" >> $GITHUB_ENV

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            venv
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          rfbrowser init

      - name: Run Robot Framework tests
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: "True"
          PYTHONPATH: resources/libraries
        run: |
          robot --outputdir results \
               --exclude skip \
               --name "E2E Tests - ${{ matrix.browser }}" \
               tests/e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-results-${{ matrix.browser }}
          path: |
            results
            screenshots

      - name: Generate test metrics
        if: always()
        run: |
          python resources/libraries/generate_metrics.py results/output.xml metrics

      - name: Upload metrics report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: metrics-report-${{ matrix.browser }}
          path: metrics
