name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox]
        include:
          - browser: chromium
            playwright-version: 1.41.1
          - browser: firefox
            playwright-version: 1.41.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Set up caching for pip dependencies
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt robotframework-metrics
          rfbrowser init

      - name: Run Robot Framework tests
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: "True"
          PYTHONPATH: ${GITHUB_WORKSPACE}/resources/libraries
        run: |
          robot --outputdir results \
               --exclude skip \
               --name "E2E Tests - ${{ matrix.browser }}" \
               tests/e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-results-${{ matrix.browser }}
          path: |
            results/*.html
            results/*.xml
            results/screenshots
          retention-days: 30
          if-no-files-found: warn

      - name: Generate metrics report
        if: always()
        run: |
          python -m robotmetrics --inputpath results/output.xml --output results/metrics_report.html

      - name: Upload metrics report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: metrics-report-${{ matrix.browser }}
          path: results/metrics_report.html
          retention-days: 30
          if-no-files-found: warn
